services:
  backend-app-primary:
    build: .
    environment:
      - IS_PRIMARY=true
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    networks:
      - backend

  backend-app:
    build: .
    depends_on:
      - redis
      - mysql
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: redis:7.2
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: coupon
    command:
      - "--max_connections=500"
    ports:
      - "3306:3306"
    networks:
      - backend

  envoy:
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"     # envoy가 외부로 노출할 포트
      - "9901:9901"     # (optional) admin UI
    depends_on:
      - backend-app
      - backend-app-primary
    networks:
      - backend

  asynqmon:
    image: hibiken/asynqmon
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge